// Code generated by "stringer -type=TagCode"; DO NOT EDIT.

package tagcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[End-0]
	_ = x[ShowFrame-1]
	_ = x[PlaceObject-4]
	_ = x[RemoveObject-5]
	_ = x[DefineBits-6]
	_ = x[JpegTables-8]
	_ = x[SetBackgroundColor-9]
	_ = x[DefineBitsLossless-20]
	_ = x[DefineBitsJpeg2-21]
	_ = x[Protect-24]
	_ = x[PlaceObject2-26]
	_ = x[RemoveObject2-28]
	_ = x[DefineBitsJpeg3-35]
	_ = x[DefineBitsLossless2-36]
	_ = x[FrameLabel-43]
	_ = x[NamedAnchor-43]
	_ = x[ExportAssets-56]
	_ = x[ImportAssets-57]
	_ = x[EnableDebugger-58]
	_ = x[EnableDebugger2-64]
	_ = x[ScriptLimits-65]
	_ = x[SetTabIndex-66]
	_ = x[FileAttributes-69]
	_ = x[PlaceObject3-70]
	_ = x[ImportAssets2-71]
	_ = x[SymbolClass-76]
	_ = x[Metadata-77]
	_ = x[DefineScalingGrid-78]
	_ = x[DefineSceneAndFrameLabelData-86]
	_ = x[DefineBinaryData-87]
	_ = x[DefineBitsJpeg4-90]
	_ = x[EnableTelemetry-93]
	_ = x[DoAction-12]
}

const _TagCode_name = "EndShowFramePlaceObjectRemoveObjectDefineBitsJpegTablesSetBackgroundColorDoActionDefineBitsLosslessDefineBitsJpeg2ProtectPlaceObject2RemoveObject2DefineBitsJpeg3DefineBitsLossless2FrameLabelExportAssetsImportAssetsEnableDebuggerEnableDebugger2ScriptLimitsSetTabIndexFileAttributesPlaceObject3ImportAssets2SymbolClassMetadataDefineScalingGridDefineSceneAndFrameLabelDataDefineBinaryDataDefineBitsJpeg4EnableTelemetry"

var _TagCode_map = map[TagCode]string{
	0:  _TagCode_name[0:3],
	1:  _TagCode_name[3:12],
	4:  _TagCode_name[12:23],
	5:  _TagCode_name[23:35],
	6:  _TagCode_name[35:45],
	8:  _TagCode_name[45:55],
	9:  _TagCode_name[55:73],
	12: _TagCode_name[73:81],
	20: _TagCode_name[81:99],
	21: _TagCode_name[99:114],
	24: _TagCode_name[114:121],
	26: _TagCode_name[121:133],
	28: _TagCode_name[133:146],
	35: _TagCode_name[146:161],
	36: _TagCode_name[161:180],
	43: _TagCode_name[180:190],
	56: _TagCode_name[190:202],
	57: _TagCode_name[202:214],
	58: _TagCode_name[214:228],
	64: _TagCode_name[228:243],
	65: _TagCode_name[243:255],
	66: _TagCode_name[255:266],
	69: _TagCode_name[266:280],
	70: _TagCode_name[280:292],
	71: _TagCode_name[292:305],
	76: _TagCode_name[305:316],
	77: _TagCode_name[316:324],
	78: _TagCode_name[324:341],
	86: _TagCode_name[341:369],
	87: _TagCode_name[369:385],
	90: _TagCode_name[385:400],
	93: _TagCode_name[400:415],
}

func (i TagCode) String() string {
	if str, ok := _TagCode_map[i]; ok {
		return str
	}
	return "TagCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
